// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameEmployee = "Employees"

// Employee mapped from table <Employees>
type Employee struct {
	EmployeeID   int32     `gorm:"column:EmployeeID;primaryKey" json:"EmployeeID"`
	FirstName    string    `gorm:"column:FirstName" json:"FirstName"`
	LastName     string    `gorm:"column:LastName" json:"LastName"`
	DepartmentID int32     `gorm:"column:DepartmentID" json:"DepartmentID"`
	HireDate     time.Time `gorm:"column:HireDate" json:"HireDate"`
}

// TableName Employee's table name
func (*Employee) TableName() string {
	return TableNameEmployee
}
