// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameOrder = "Orders"

// Order mapped from table <Orders>
type Order struct {
	OrderID     int32     `gorm:"column:OrderID;primaryKey" json:"OrderID"`
	CustomerID  int32     `gorm:"column:CustomerID" json:"CustomerID"`
	OrderDate   time.Time `gorm:"column:OrderDate" json:"OrderDate"`
	TotalAmount float64   `gorm:"column:TotalAmount" json:"TotalAmount"`
}

// TableName Order's table name
func (*Order) TableName() string {
	return TableNameOrder
}
