// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNamePERSON = "PEOPLE"

// PERSON mapped from table <PEOPLE>
type PERSON struct {
	ID        int32  `gorm:"column:id" json:"id"`
	FirstName string `gorm:"column:first_name" json:"first_name"`
	LastName  string `gorm:"column:last_name" json:"last_name"`
	Email     string `gorm:"column:email" json:"email"`
	Gender    string `gorm:"column:gender" json:"gender"`
	IPAddress string `gorm:"column:ip_address" json:"ip_address"`
}

// TableName PERSON's table name
func (*PERSON) TableName() string {
	return TableNamePERSON
}
