// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameProduct = "Products"

// Product mapped from table <Products>
type Product struct {
	ProductID   int32   `gorm:"column:ProductID;primaryKey" json:"ProductID"`
	ProductName string  `gorm:"column:ProductName" json:"ProductName"`
	UnitPrice   float64 `gorm:"column:UnitPrice" json:"UnitPrice"`
	InStock     int32   `gorm:"column:InStock" json:"InStock"`
}

// TableName Product's table name
func (*Product) TableName() string {
	return TableNameProduct
}
